#!/usr/bin/env python

# reads json file generated by get_protein_data.py
# and writes a csv file with the columns:
#     name, type, upid
# where upid is the UniProtKB id.

import sys
import csv
import json

fname = sys.argv[1]

with open('uniprot.json') as f:
    prots = json.load(f)

prots = [p for p in prots if p['organism'].startswith('Homo sapiens')]

with open('entity_names.csv', 'wb') as f:
    writer = csv.writer(f)
    writer.writerow(['name', 'type', 'upid'])
    for p in prots:
        upid = p['id']
        for name in p['protein']:
            writer.writerow([name, 'protein', upid])
        if 'gene' in p:
            for name in p['gene']:
                writer.writerow([name, 'gene', upid])
            
